import { test, expect } from '@playwright/test';

test.describe('AutoTube YouTube Video Generator', () => {

  test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => {
      localStorage.setItem('autotube_onboarding_seen', 'true');
    });
  });

  test('app loads and shows topic page', async ({ page }) => {
    await page.goto('/');
    await expect(page).toHaveTitle(/AutoTube/);
    await expect(page.locator('h1:has-text("AutoTube")')).toBeVisible();
    await expect(page.locator('h2:has-text("Choose Your Video Topic")')).toBeVisible();
    await expect(page.getByTestId('topic-input')).toBeVisible();
    await expect(page.getByTestId('generate-script-only')).toBeVisible();
  });

  test('sidebar shows all pipeline steps', async ({ page }) => {
    await page.goto('/');
    const steps = [
      'sidebar-step-topic',
      'sidebar-step-script',
      'sidebar-step-media',
      'sidebar-step-narration',
      'sidebar-step-assembly',
      'sidebar-step-preview',
    ];
    for (const step of steps) {
      await expect(page.getByTestId(step)).toBeVisible();
    }
  });

  test('topic step shows suggested topics', async ({ page }) => {
    await page.goto('/');
    await expect(page.locator('text=Trending Topics')).toBeVisible({ timeout: 30000 });
    await expect(page.getByTestId('suggested-topic-0')).toBeVisible({ timeout: 30000 });
    await expect(page.getByTestId('style-business_insider')).toBeVisible();
    await expect(page.getByTestId('style-warfront')).toBeVisible();
    await expect(page.getByTestId('style-documentary')).toBeVisible();
    await expect(page.getByTestId('style-explainer')).toBeVisible();
  });

  test('can select a suggested topic', async ({ page }) => {
    await page.goto('/');
    // Wait for LLM-generated topics to load
    await expect(page.getByTestId('suggested-topic-0')).toBeVisible({ timeout: 30000 });
    await page.getByTestId('suggested-topic-0').click();
    const input = page.getByTestId('topic-input');
    // Topics are randomly generated by LLM each time, just verify something was filled
    await expect(input).not.toHaveValue('');
  });

  test('generate button disabled without topic', async ({ page }) => {
    await page.goto('/');
    const input = page.getByTestId('topic-input');
    await input.fill('');
    const btn = page.getByTestId('generate-script-only');
    await expect(btn).toBeDisabled();
  });

  test('can generate script with LLM', async ({ page }) => {
    await page.goto('/');
    const input = page.getByTestId('topic-input');
    await input.fill('Test Video Topic');
    await page.getByTestId('generate-script-only').click();

    // Should navigate to script step with processing
    await expect(page.getByRole('heading', { name: 'Generating Script' })).toBeVisible({ timeout: 10000 });

    // Wait for processing to complete (LLM calls can take up to 60s)
    await expect(page.locator('text=Step 2 — Complete')).toBeVisible({ timeout: 90000 });
    await expect(page.locator('text=Review and edit')).toBeVisible({ timeout: 5000 });

    // Should show script segments and the source media button
    await expect(page.locator('text=Source Media Assets')).toBeVisible({ timeout: 5000 });
  });

  test('script step shows expandable segments', async ({ page }) => {
    await page.goto('/');
    const input = page.getByTestId('topic-input');
    await input.fill('Test Topic');
    await page.getByTestId('generate-script-only').click();

    // Wait for script generation (LLM can take up to 60s)
    await expect(page.locator('text=Step 2 — Complete')).toBeVisible({ timeout: 90000 });

    // Should have segment buttons with type labels (intro, section, outro)
    const segmentButtons = page.locator('button:has(span.font-mono)');
    await expect(segmentButtons.first()).toBeVisible({ timeout: 5000 });

    // Click to expand a segment
    await segmentButtons.first().click();
    await expect(page.locator('text=Narration Text')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('text=Visual Direction')).toBeVisible({ timeout: 5000 });
  });

  test('can proceed to media sourcing', async ({ page }) => {
    await page.goto('/');
    const input = page.getByTestId('topic-input');
    await input.fill('Test Topic');
    await page.getByTestId('generate-script-only').click();

    // Wait for script generation (LLM can take up to 60s)
    await expect(page.locator('text=Source Media Assets')).toBeVisible({ timeout: 90000 });

    // Click to source media
    await page.locator('button:has-text("Source Media Assets")').click();

    // Should show media step with processing
    await expect(page.locator('text=AI Visual Director at Work')).toBeVisible({ timeout: 10000 });
  });

  test('sidebar narration and assembly steps expose actions instead of dead-ending', async ({ page }) => {
    test.setTimeout(600000); // 10 minutes — narration uses real TTS
    await page.goto('/');

    await page.getByTestId('topic-input').fill('Test Topic');
    await page.getByTestId('generate-script-only').click();

    await expect(page.locator('button:has-text("Source Media Assets")')).toBeVisible({ timeout: 90000 });
    await page.locator('button:has-text("Source Media Assets")').click();

    await page.getByTestId('sidebar-step-narration').click();
    await expect(page.getByTestId('prepare-narration-button')).toBeVisible();

    await page.getByTestId('prepare-narration-button').click();
    await expect(page.locator('text=Step 4 — Complete')).toBeVisible({ timeout: 600000 });

    await page.getByTestId('sidebar-step-assembly').click();
    await expect(page.getByTestId('assemble-video-button')).toBeVisible();
  });

  test('settings modal opens and closes', async ({ page }) => {
    await page.goto('/');
    await page.getByTestId('sidebar-settings-button').click();
    await expect(page.getByTestId('settings-modal')).toBeVisible({ timeout: 3000 });
    await expect(page.locator('text=OpenRouter API Key')).toBeVisible({ timeout: 3000 });
    await expect(page.locator('text=Flickr API Key')).toBeVisible({ timeout: 3000 });

    // Close modal
    await page.getByTestId('settings-modal-close').click();
    await expect(page.getByTestId('settings-modal')).not.toBeVisible({ timeout: 3000 });
  });

  test('debug overlay is accessible', async ({ page }) => {
    await page.goto('/');
    // Debug toggle should be visible
    const debugBtn = page.locator('button[title="Open System Logs"]');
    await expect(debugBtn).toBeVisible({ timeout: 3000 });
  });

  test('style selection works', async ({ page }) => {
    await page.goto('/');
    await page.getByTestId('style-warfront').click();
    await page.getByTestId('style-documentary').click();
    await page.getByTestId('style-explainer').click();

    // Verify topic input still works
    const input = page.getByTestId('topic-input');
    await expect(input).toBeVisible();
  });

  test('tone selection works', async ({ page }) => {
    await page.goto('/');
    await page.getByTestId('tone-dramatic').click();
    await page.getByTestId('tone-urgent').click();
    await page.getByTestId('tone-casual').click();
  });

  test('duration selector works', async ({ page }) => {
    await page.goto('/');
    const select = page.getByTestId('duration-select');
    await select.selectOption('10');
    await expect(select).toHaveValue('10');
    await select.selectOption('3');
    await expect(select).toHaveValue('3');
  });

  test('no console errors on initial load', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto('/');
    await expect(page.locator('h1:has-text("AutoTube")')).toBeVisible();

    // Filter out expected React dev warnings
    const realErrors = errors.filter(e =>
      !e.includes('React DevTools') &&
      !e.includes('fast-refresh')
    );
    expect(realErrors).toEqual([]);
  });

  test('progress bar visible in sidebar', async ({ page }) => {
    await page.goto('/');
    await expect(page.locator('text=PROGRESS')).toBeVisible({ timeout: 3000 });
  });

  // Verify error handling when OpenRouter API returns 500
  test('shows error state when OpenRouter API returns 500', async ({ page }) => {
    // Intercept the OpenRouter API endpoint and return a 500 error
    await page.route('**/openrouter.ai/**', (route) => {
      route.fulfill({
        status: 500,
        contentType: 'application/json',
        body: JSON.stringify({ error: 'Internal Server Error' }),
      });
    });

    await page.goto('/');

    // Fill in a topic and click generate
    const input = page.getByTestId('topic-input');
    await input.fill('The History of the Internet');
    await page.getByTestId('generate-script-only').click();

    // The app should show the generating state
    await expect(page.getByRole('heading', { name: 'Generating Script' })).toBeVisible({ timeout: 10000 });

    // When the API fails, the app shows an error message
    await expect(page.locator('text=Script generation failed')).toBeVisible({ timeout: 30000 });
  });

  test('full pipeline: topic → script → media', async ({ page }) => {
    await page.goto('/');

    // Step 1: Enter topic
    await page.getByTestId('topic-input').fill('The Future of AI');
    await page.getByTestId('generate-script-only').click();

    // Wait for script (LLM can take up to 60s)
    await expect(page.locator('text=Source Media Assets')).toBeVisible({ timeout: 90000 });

    // Step 2: Go to media
    await page.locator('button:has-text("Source Media Assets")').click();

    // Should show media processing
    await expect(page.locator('text=AI Visual Director at Work')).toBeVisible({ timeout: 10000 });

    // Wait for media to complete or show results
    const hasResults = await page.locator('text=Visual Director Output').isVisible({ timeout: 60000 }).catch(() => false);
    const hasProcessing = await page.locator('text=harvesting').isVisible({ timeout: 5000 }).catch(() => false);
    const hasResearch = await page.locator('text=Researching').isVisible({ timeout: 5000 }).catch(() => false);

    // Either it completed with results or is still processing (which means the pipeline works)
    expect(hasResults || hasProcessing || hasResearch).toBe(true);
  });
});
