/**
 * Preservation Property Tests — Clean JSON Parses Directly and Garbage Returns Null
 *
 * These tests verify behaviors that MUST be preserved after the fix is implemented:
 * 1. Clean JSON (no fences, no prose) parses correctly through extractJson
 * 2. Strings with no JSON structure return null
 * 3. validateVisualPlan works correctly with pre-parsed objects
 *
 * EXPECTED: These tests PASS on unfixed code (they confirm baseline behavior).
 *
 * Validates: Requirements 3.4, 3.5, 3.6
 */
import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { extractJson } from '../extractJson';
import { validateVisualPlan } from '../../services/llmVisualDirector';

// ---------------------------------------------------------------------------
// Property 1: Clean JSON Preservation
// ---------------------------------------------------------------------------

describe('Preservation: Clean JSON Parses Directly', () => {
  /**
   * **Validates: Requirements 3.4**
   *
   * Property: For all valid JSON objects generated by fc.jsonValue(),
   * extractJson(JSON.stringify(obj)) deep-equals obj.
   * Clean JSON passes through unchanged — no fences, no prose, just valid JSON.
   *
   * Note: We use fc.dictionary with safe value types to avoid the -0/+0
   * serialization edge case (JSON.stringify(-0) === "0", JSON.parse("0") === 0).
   */
  it('extractJson returns parsed object for all valid JSON objects', () => {
    // Generate JSON objects that round-trip cleanly through JSON.stringify/parse
    const safeJsonObj = fc.dictionary(
      fc.string({ minLength: 1, maxLength: 10 }),
      fc.oneof(
        fc.integer({ min: -1000, max: 1000 }),
        fc.string({ maxLength: 20 }),
        fc.boolean(),
        fc.constant(null),
        fc.array(fc.oneof(fc.integer(), fc.string({ maxLength: 10 }), fc.boolean()), { maxLength: 3 }),
      ),
      { minKeys: 1, maxKeys: 5 },
    );

    fc.assert(
      fc.property(
        safeJsonObj,
        (obj) => {
          const jsonStr = JSON.stringify(obj);
          const result = extractJson(jsonStr);
          expect(result).toEqual(JSON.parse(jsonStr));
        },
      ),
      { numRuns: 200 },
    );
  });

  /**
   * **Validates: Requirements 3.4**
   *
   * Property: For valid JSON arrays, extractJson returns the parsed array.
   */
  it('extractJson returns parsed array for valid JSON arrays', () => {
    const safeJsonArr = fc.array(
      fc.oneof(
        fc.integer({ min: -1000, max: 1000 }),
        fc.string({ maxLength: 20 }),
        fc.boolean(),
        fc.constant(null),
      ),
      { minLength: 1, maxLength: 5 },
    );

    fc.assert(
      fc.property(
        safeJsonArr,
        (arr) => {
          const jsonStr = JSON.stringify(arr);
          const result = extractJson(jsonStr);
          expect(result).toEqual(arr);
        },
      ),
      { numRuns: 100 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 2: Garbage Returns Null
// ---------------------------------------------------------------------------

describe('Preservation: Garbage Returns Null', () => {
  /**
   * **Validates: Requirements 3.5**
   *
   * Property: For all strings that do NOT contain '{' or '[' and are NOT
   * valid JSON primitives (numbers, booleans, null, quoted strings),
   * extractJson(str) returns null. Content with no JSON structure
   * must gracefully return null without crashing.
   */
  it('extractJson returns null for strings without JSON structure', () => {
    // Generate strings that cannot be valid JSON:
    // - No { or [ (so not objects/arrays)
    // - Filter out anything that JSON.parse would accept (numbers, booleans, null, quoted strings)
    const garbageArb = fc.string({ minLength: 1, maxLength: 50 })
      .filter((s) => !s.includes('{') && !s.includes('['))
      .filter((s) => {
        // Exclude strings that happen to be valid JSON primitives
        try { JSON.parse(s); return false; } catch { return true; }
      });

    fc.assert(
      fc.property(
        garbageArb,
        (str) => {
          const result = extractJson(str);
          expect(result).toBeNull();
        },
      ),
      { numRuns: 200 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 3: validateVisualPlan Unchanged
// ---------------------------------------------------------------------------

describe('Preservation: validateVisualPlan works with pre-parsed objects', () => {
  /**
   * **Validates: Requirements 3.6**
   *
   * Property: For all valid plan objects with at least one shot containing
   * a non-empty (non-whitespace) concept and queries array,
   * validateVisualPlan returns shots.length > 0.
   * The function itself works correctly with pre-parsed objects.
   */
  it('validateVisualPlan returns shots when given valid plan objects', () => {
    // Generator for a valid shot object with non-whitespace concept
    const shotArb = fc.record({
      concept: fc.string({ minLength: 2, maxLength: 30 }).filter(s => s.trim().length > 0),
      queries: fc.array(
        fc.string({ minLength: 2, maxLength: 20 }).filter(s => s.trim().length > 0),
        { minLength: 1, maxLength: 3 },
      ),
      vibe: fc.string({ minLength: 1, maxLength: 15 }),
    });

    // Generator for a valid visual plan with primaryShot
    const planArb = fc.record({
      intent: fc.string({ minLength: 1, maxLength: 50 }),
      primaryShot: shotArb,
      visualConcept: fc.string({ minLength: 1, maxLength: 30 }),
    });

    fc.assert(
      fc.property(
        planArb,
        (plan) => {
          const result = validateVisualPlan(plan, 'fallback topic');
          expect(result.shots).toBeDefined();
          expect(result.shots!.length).toBeGreaterThan(0);
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 3.6**
   *
   * Property: For plan objects with both primaryShot and secondaryShot
   * (with distinct concepts), validateVisualPlan returns at least 2 shots.
   */
  it('validateVisualPlan returns multiple shots for plans with primary and secondary', () => {
    const shotArb = (prefix: string) => fc.record({
      concept: fc.string({ minLength: 2, maxLength: 20 }).filter(s => s.trim().length > 0).map(s => prefix + s),
      queries: fc.array(
        fc.string({ minLength: 2, maxLength: 20 }).filter(s => s.trim().length > 0),
        { minLength: 1, maxLength: 3 },
      ),
      vibe: fc.string({ minLength: 1, maxLength: 15 }),
    });

    const planArb = fc.record({
      intent: fc.string({ minLength: 1, maxLength: 50 }),
      primaryShot: shotArb('primary_'),
      secondaryShot: shotArb('secondary_'),
      visualConcept: fc.string({ minLength: 1, maxLength: 30 }),
    });

    fc.assert(
      fc.property(
        planArb,
        (plan) => {
          const result = validateVisualPlan(plan, 'fallback topic');
          expect(result.shots).toBeDefined();
          expect(result.shots!.length).toBeGreaterThanOrEqual(2);
        },
      ),
      { numRuns: 100 },
    );
  });
});
