/**
 * Property-Based Tests — Editing Rhythm
 *
 * Feature: video-quality-max, Properties 23, 24, 25, 26, 27
 *
 * Validates: Requirements 10.1, 10.2, 10.3, 10.4, 10.5
 */
import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import {
  planSegmentShots,
  alternateFraming,
  planTextCards,
  DEFAULT_EDITING_RHYTHM_CONFIG,
} from '../renderer/editingRhythm';
import type { ScriptSegment, MediaAsset } from '../../types';

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

/** Arbitrary for a valid segment type */
const segmentTypeArb: fc.Arbitrary<ScriptSegment['type']> = fc.constantFrom(
  'intro',
  'section',
  'transition',
  'outro',
);

/** Arbitrary for narration text that produces >8 seconds estimated duration (>20 words at 2.5 wps) */
const longNarrationArb: fc.Arbitrary<string> = fc
  .array(
    fc.constantFrom(
      'revenue', 'growth', 'market', 'company', 'investors', 'analysts',
      'reported', 'significant', 'decline', 'across', 'major', 'business',
      'segments', 'geographic', 'regions', 'leading', 'widespread', 'concern',
      'previously', 'optimistic', 'outlook', 'quarterly', 'earnings', 'exceeded',
      'expectations', 'dramatically', 'transformed', 'industry', 'landscape',
      'fundamentally', 'disrupted', 'traditional', 'approaches', 'strategies',
    ),
    { minLength: 21, maxLength: 60 },
  )
  .map((words) => words.join(' ') + '.');

/** Arbitrary for short narration text that produces <=8 seconds (<=20 words) */
const shortNarrationArb: fc.Arbitrary<string> = fc
  .array(
    fc.constantFrom(
      'The', 'market', 'grew', 'this', 'year', 'rapidly', 'and', 'strongly',
      'with', 'great', 'results', 'overall',
    ),
    { minLength: 1, maxLength: 10 },
  )
  .map((words) => words.join(' ') + '.');

/** Arbitrary for narration with statistical content */
const statisticalNarrationArb: fc.Arbitrary<string> = fc.oneof(
  fc.tuple(
    fc.constantFrom('The company lost', 'Revenue reached', 'They invested'),
    fc.integer({ min: 1, max: 999 }),
    fc.constantFrom(' billion', ' million', ' trillion'),
    fc.constantFrom(' in revenue.', ' last year.', ' this quarter.'),
  ).map(([prefix, num, magnitude, suffix]) => `${prefix} $${num}${magnitude}${suffix}`),
  fc.tuple(
    fc.constantFrom('Growth was', 'The market dropped', 'Adoption increased by'),
    fc.integer({ min: 1, max: 99 }),
    fc.constantFrom(' this year.', ' in Q4.', ' since launch.'),
  ).map(([prefix, pct, suffix]) => `${prefix} ${pct}%${suffix}`),
);

/** Arbitrary for a ScriptSegment with configurable duration and narration */
function segmentArb(opts?: {
  minDuration?: number;
  maxDuration?: number;
  narrationArb?: fc.Arbitrary<string>;
}): fc.Arbitrary<ScriptSegment> {
  const minDur = opts?.minDuration ?? 1;
  const maxDur = opts?.maxDuration ?? 60;
  const narrArb = opts?.narrationArb ?? fc.constant('Some narration text here.');

  return fc.record({
    id: fc.uuid(),
    type: segmentTypeArb,
    title: fc.constantFrom('Introduction', 'Market Analysis', 'Key Findings', 'Conclusion'),
    narration: narrArb,
    visualNote: fc.constant('Show relevant imagery'),
    duration: fc.double({ min: minDur, max: maxDur, noNaN: true, noDefaultInfinity: true }),
  });
}

/** Arbitrary for a MediaAsset */
const mediaAssetArb: fc.Arbitrary<MediaAsset> = fc.record({
  id: fc.uuid(),
  segmentId: fc.uuid(),
  type: fc.constantFrom('image' as const, 'video' as const),
  url: fc.webUrl(),
  alt: fc.constantFrom('Chart showing growth', 'Person speaking', 'Building exterior'),
  source: fc.constantFrom('pexels', 'unsplash', 'pixabay'),
});

/** Arbitrary for a non-empty array of media assets */
const assetsArb: fc.Arbitrary<MediaAsset[]> = fc.array(mediaAssetArb, { minLength: 1, maxLength: 5 });

// ---------------------------------------------------------------------------
// Property 23: Maximum Visual Hold Time
// ---------------------------------------------------------------------------

describe('Feature: video-quality-max, Property 23: Maximum Visual Hold Time', () => {
  /**
   * **Validates: Requirements 10.1**
   *
   * For any shot plan generated by planSegmentShots, no single static image
   * shot SHALL exceed 5 seconds duration without a cut, zoom, or transition.
   */

  it('no shot exceeds maxHoldTimeSec (4 seconds) in duration', () => {
    fc.assert(
      fc.property(
        segmentArb({ minDuration: 1, maxDuration: 60 }),
        assetsArb,
        (segment, assets) => {
          const shots = planSegmentShots(segment, assets, DEFAULT_EDITING_RHYTHM_CONFIG);

          for (const shot of shots) {
            const shotDuration = shot.endTime - shot.startTime;
            expect(shotDuration).toBeLessThanOrEqual(
              DEFAULT_EDITING_RHYTHM_CONFIG.maxHoldTimeSec + 0.001,
            );
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  it('all shots have valid time ranges (startTime < endTime)', () => {
    fc.assert(
      fc.property(
        segmentArb({ minDuration: 1, maxDuration: 60 }),
        assetsArb,
        (segment, assets) => {
          const shots = planSegmentShots(segment, assets, DEFAULT_EDITING_RHYTHM_CONFIG);

          for (const shot of shots) {
            expect(shot.endTime).toBeGreaterThan(shot.startTime);
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  it('shot plan covers the full segment duration without gaps', () => {
    fc.assert(
      fc.property(
        segmentArb({ minDuration: 1, maxDuration: 60 }),
        assetsArb,
        (segment, assets) => {
          const shots = planSegmentShots(segment, assets, DEFAULT_EDITING_RHYTHM_CONFIG);

          if (shots.length > 0) {
            expect(shots[0].startTime).toBeCloseTo(0, 3);
            expect(shots[shots.length - 1].endTime).toBeCloseTo(segment.duration, 3);
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 24: Shot Splitting for Long Narration
// ---------------------------------------------------------------------------

describe('Feature: video-quality-max, Property 24: Shot Splitting for Long Narration', () => {
  /**
   * **Validates: Requirements 10.2**
   *
   * For any segment with narration duration exceeding 8 seconds,
   * planSegmentShots SHALL return at least 2 shots with a cut or motion change.
   */

  it('segments with narration >8 seconds produce at least 2 shots', () => {
    fc.assert(
      fc.property(
        segmentArb({ minDuration: 9, maxDuration: 60, narrationArb: longNarrationArb }),
        assetsArb,
        (segment, assets) => {
          const shots = planSegmentShots(segment, assets, DEFAULT_EDITING_RHYTHM_CONFIG);

          // Long narration (>20 words at 2.5 wps = >8s) should produce ≥2 shots
          expect(shots.length).toBeGreaterThanOrEqual(2);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('each shot in a split plan has a different motion type or time boundary', () => {
    fc.assert(
      fc.property(
        segmentArb({ minDuration: 9, maxDuration: 30, narrationArb: longNarrationArb }),
        assetsArb,
        (segment, assets) => {
          const shots = planSegmentShots(segment, assets, DEFAULT_EDITING_RHYTHM_CONFIG);

          if (shots.length >= 2) {
            // Verify shots are sequential (cut/transition between them)
            for (let i = 1; i < shots.length; i++) {
              expect(shots[i].startTime).toBeCloseTo(shots[i - 1].endTime, 3);
            }
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 25: Framing Alternation
// ---------------------------------------------------------------------------

describe('Feature: video-quality-max, Property 25: Framing Alternation', () => {
  /**
   * **Validates: Requirements 10.3**
   *
   * For any pair of consecutive segment indices i and i+1,
   * alternateFraming(i) SHALL return a different framing value than
   * alternateFraming(i+1).
   */

  it('consecutive segment indices produce different framing values', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 10000 }),
        (segmentIndex) => {
          const framingCurrent = alternateFraming(segmentIndex);
          const framingNext = alternateFraming(segmentIndex + 1);

          expect(framingCurrent).not.toBe(framingNext);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('framing values are always either close_up or wide_angle', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 10000 }),
        (segmentIndex) => {
          const framing = alternateFraming(segmentIndex);

          expect(['close_up', 'wide_angle']).toContain(framing);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('even indices always produce close_up and odd indices always produce wide_angle', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 5000 }),
        (n) => {
          expect(alternateFraming(n * 2)).toBe('close_up');
          expect(alternateFraming(n * 2 + 1)).toBe('wide_angle');
        },
      ),
      { numRuns: 100 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 26: Animated Text Card Insertion
// ---------------------------------------------------------------------------

describe('Feature: video-quality-max, Property 26: Animated Text Card Insertion', () => {
  /**
   * **Validates: Requirements 10.4**
   *
   * For any video with more than 5 segments, the render plan SHALL include
   * at least 2 animated text cards distributed across the video.
   */

  it('videos with >5 segments include at least 2 animated text cards', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 6, max: 20 }),
        fc.boolean(),
        (segmentCount, useStatistical) => {
          const segments: ScriptSegment[] = Array.from({ length: segmentCount }, (_, i) => ({
            id: `seg-${i}`,
            type: 'section' as const,
            title: `Section ${i}`,
            narration: useStatistical && i % 2 === 0
              ? `The company earned $${(i + 1) * 10} billion in revenue this quarter.`
              : `This segment discusses important topics about the industry landscape and future trends.`,
            visualNote: 'Show relevant imagery',
            duration: 5 + i,
          }));

          const cards = planTextCards(segments);

          expect(cards.length).toBeGreaterThanOrEqual(2);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('videos with <=5 segments produce no text cards', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 5 }),
        (segmentCount) => {
          const segments: ScriptSegment[] = Array.from({ length: segmentCount }, (_, i) => ({
            id: `seg-${i}`,
            type: 'section' as const,
            title: `Section ${i}`,
            narration: `Revenue grew by ${(i + 1) * 15}% this quarter.`,
            visualNote: 'Show chart',
            duration: 5,
          }));

          const cards = planTextCards(segments);

          expect(cards.length).toBe(0);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('text cards are distributed across different segments', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 6, max: 15 }),
        (segmentCount) => {
          const segments: ScriptSegment[] = Array.from({ length: segmentCount }, (_, i) => ({
            id: `seg-${i}`,
            type: 'section' as const,
            title: `Section ${i}`,
            narration: `The market grew by ${(i + 1) * 5}% reaching $${(i + 1) * 100} million.`,
            visualNote: 'Show chart',
            duration: 6,
          }));

          const cards = planTextCards(segments);
          const segmentIndices = cards.map((c) => c.segmentIndex);
          const uniqueIndices = new Set(segmentIndices);

          // Cards should be on different segments
          expect(uniqueIndices.size).toBe(cards.length);
        },
      ),
      { numRuns: 100 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 27: Maximum Asset Display Without Change
// ---------------------------------------------------------------------------

describe('Feature: video-quality-max, Property 27: Maximum Asset Display Without Change', () => {
  /**
   * **Validates: Requirements 10.5**
   *
   * For any shot plan, no single visual asset SHALL appear for more than 7
   * consecutive seconds without a motion type change or overlay change.
   */

  it('no shot exceeds maxAssetTimeSec (7 seconds) without motion change', () => {
    fc.assert(
      fc.property(
        segmentArb({ minDuration: 1, maxDuration: 60 }),
        assetsArb,
        (segment, assets) => {
          const shots = planSegmentShots(segment, assets, DEFAULT_EDITING_RHYTHM_CONFIG);

          for (const shot of shots) {
            const shotDuration = shot.endTime - shot.startTime;
            expect(shotDuration).toBeLessThanOrEqual(
              DEFAULT_EDITING_RHYTHM_CONFIG.maxAssetTimeSec + 0.001,
            );
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  it('consecutive shots with the same asset have different motion types', () => {
    fc.assert(
      fc.property(
        segmentArb({ minDuration: 8, maxDuration: 30 }),
        fc.array(mediaAssetArb, { minLength: 1, maxLength: 2 }),
        (segment, assets) => {
          const shots = planSegmentShots(segment, assets, DEFAULT_EDITING_RHYTHM_CONFIG);

          for (let i = 1; i < shots.length; i++) {
            if (shots[i].assetIndex === shots[i - 1].assetIndex) {
              // Same asset in consecutive shots must have different motion types
              // (this ensures a visual change occurs)
              expect(shots[i].motionType !== shots[i - 1].motionType ||
                     shots[i].startTime !== shots[i - 1].startTime).toBe(true);
            }
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  it('total consecutive time for same asset without motion change never exceeds 7s', () => {
    fc.assert(
      fc.property(
        segmentArb({ minDuration: 1, maxDuration: 60 }),
        assetsArb,
        (segment, assets) => {
          const shots = planSegmentShots(segment, assets, DEFAULT_EDITING_RHYTHM_CONFIG);

          // Track consecutive time for same asset + same motion type + same rate
          // Ken Burns shots with different rates constitute visual change
          let consecutiveTime = 0;
          let prevAssetIndex = -1;
          let prevMotionType = '';
          let prevKenBurnsRate: number | undefined = undefined;

          for (const shot of shots) {
            const shotDuration = shot.endTime - shot.startTime;

            const sameAsset = shot.assetIndex === prevAssetIndex;
            const sameMotion = shot.motionType === prevMotionType;
            const sameRate = shot.kenBurnsRate === prevKenBurnsRate;

            if (sameAsset && sameMotion && sameRate) {
              consecutiveTime += shotDuration;
            } else {
              consecutiveTime = shotDuration;
            }

            expect(consecutiveTime).toBeLessThanOrEqual(
              DEFAULT_EDITING_RHYTHM_CONFIG.maxAssetTimeSec + 0.001,
            );

            prevAssetIndex = shot.assetIndex;
            prevMotionType = shot.motionType;
            prevKenBurnsRate = shot.kenBurnsRate;
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
