/**
 * WebVTT Subtitle Parser
 *
 * Parses word-level WebVTT files generated by edge-tts --write-subtitles
 * and extracts per-word timestamps for karaoke-style caption sync.
 */

import { readFileSync, existsSync } from 'fs';

/**
 * @typedef {Object} WordTimestamp
 * @property {string} word - The spoken word
 * @property {number} start - Start time in seconds
 * @property {number} end - End time in seconds
 */

/**
 * Parse a WebVTT file and extract word-level timestamps.
 *
 * edge-tts generates VTT with cues like:
 *   00:00:00.000 --> 00:00:00.500
 *   Each
 *
 *   00:00:00.500 --> 00:00:01.000
 *   test
 *
 * Each cue contains one word with its timing.
 *
 * @param {string} vttPath - Path to the .vtt file
 * @returns {WordTimestamp[]} Array of word timestamps
 */
export function parseVttWordTimestamps(vttPath) {
  if (!existsSync(vttPath)) return [];

  let content;
  try {
    content = readFileSync(vttPath, 'utf8');
  } catch (err) {
    console.error(`  ⚠ Failed to read VTT file: ${vttPath}: ${err.message}`);
    return [];
  }
  const lines = content.split('\n');

  /** @type {WordTimestamp[]} */
  const words = [];
  let i = 0;

  // Skip WEBVTT header
  while (i < lines.length && !lines[i].includes('-->')) {
    i++;
  }

  while (i < lines.length) {
    const line = lines[i].trim();

    // Look for timestamp line: 00:00:00.000 --> 00:00:00.500
    if (line.includes('-->')) {
      const [startStr, endStr] = line.split('-->').map(s => s.trim());
      const start = parseVttTimestamp(startStr);
      const end = parseVttTimestamp(endStr);

      // Next non-empty line(s) are the word(s)
      i++;
      const wordLines = [];
      while (i < lines.length && lines[i].trim() !== '' && !lines[i].includes('-->')) {
        wordLines.push(lines[i].trim());
        i++;
      }

      const word = wordLines.join(' ').trim();
      if (word && !isNaN(start) && !isNaN(end)) {
        words.push({ word, start, end });
      }
    } else {
      i++;
    }
  }

  return words;
}

/**
 * Parse a VTT timestamp string (HH:MM:SS.mmm or MM:SS.mmm or SS.mmm) to seconds.
 * @param {string} str
 * @returns {number}
 */
function parseVttTimestamp(str) {
  const normalized = str.replace(',', '.');
  const parts = normalized.split(':');
  let seconds = 0;

  if (parts.length === 3) {
    const h = parseFloat(parts[0]);
    const m = parseFloat(parts[1]);
    const s = parseFloat(parts[2]);
    if (isNaN(h) || isNaN(m) || isNaN(s)) return NaN;
    seconds = h * 3600 + m * 60 + s;
  } else if (parts.length === 2) {
    const m = parseFloat(parts[0]);
    const s = parseFloat(parts[1]);
    if (isNaN(m) || isNaN(s)) return NaN;
    seconds = m * 60 + s;
  } else if (parts.length === 1) {
    seconds = parseFloat(parts[0]);
    if (isNaN(seconds)) return NaN;
  }

  return seconds;
}

/**
 * Given a progress value (0-1) and word timestamps, find the current word index.
 * Falls back to uniform distribution if no timestamps available.
 *
 * @param {number} progress - 0 to 1 progress within the segment
 * @param {number} segmentDuration - Total segment duration in seconds (planned video timeline)
 * @param {WordTimestamp[]} wordTimestamps - Word timestamps from VTT (may be empty)
 * @param {number} totalWords - Total word count (for fallback uniform distribution)
 * @param {number} [lastIndex=0] - Index to start scanning from (optimization)
 * @param {number} [actualAudioDuration] - Actual audio duration in seconds (from audio metadata)
 * @returns {{ wordIndex: number, windowStart: number, windowEnd: number }}
 */
export function findCurrentWord(progress, segmentDuration, wordTimestamps, totalWords, lastIndex = 0, actualAudioDuration) {
  // If we have real word timestamps, use them
  if (wordTimestamps.length > 0 && segmentDuration > 0) {
    // Map progress (0-1 within segment) to video time, then find the word.
    // segmentDuration is the planned segment length (e.g. 6s).
    // VTT timestamps are relative to audio start, which aligns with segment start.
    // If actualAudioDuration differs from segmentDuration, scale accordingly.
    const duration = actualAudioDuration && actualAudioDuration > 0 ? actualAudioDuration : segmentDuration;
    const currentTime = progress * duration;

    // Optimize: start scanning from lastIndex (avoid O(n) scan per frame)
    let wordIndex = lastIndex;
    // If lastIndex is past currentTime, scan backwards
    if (wordTimestamps[lastIndex] && wordTimestamps[lastIndex].start > currentTime) {
      wordIndex = 0;
    }
    for (let i = wordIndex; i < wordTimestamps.length; i++) {
      if (wordTimestamps[i].start <= currentTime) {
        wordIndex = i;
      } else {
        break;
      }
    }

    // Sliding window: show last 6 words + current
    const windowStart = Math.max(0, wordIndex - 6);
    const windowEnd = Math.min(wordTimestamps.length, wordIndex + 1);

    return { wordIndex, windowStart, windowEnd };
  }

  // Fallback: uniform distribution (existing behavior)
  const wordIndex = Math.min(Math.floor(progress * totalWords), totalWords - 1);
  const windowStart = Math.max(0, wordIndex - 6);
  const windowEnd = Math.min(totalWords, wordIndex + 1);

  return { wordIndex, windowStart, windowEnd };
}
